name: ELarAppAutomationSmoke

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: read
  checks: write     # <-- required for posting annotations

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & test
        run: mvn -B test -Psmoke -Dcucumber.plugin="pretty, json:target/cucumber.json"
      - name: Publish Cucumber Report to Annotations
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.4
        with:
          path: target/cucumber.json
          access-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cucumber-json
          path: target/cucumber.json