name: ElarAppAutomationSmoke

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & test
        run: mvn test -Psmoke
      - name: Publish Cucumber Report to Annotations
        if: always()
        uses: deblockt/cucumber-report-annotations-action@v1.4
        with:
          path: target/cucumber.json
